version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/otp_twilio?schema=public
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - OTP_EXPIRATION_MINUTES=${OTP_EXPIRATION_MINUTES:-10}
      - JWT_SECRET=${JWT_SECRET:-supersecretkey}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN:-1h}
      - PORT=3000

  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=otp_twilio
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: